apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgsbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgsbuggy
  template:
    metadata:
      labels:
        app: cgsbuggy
    spec:
      containers:
      - name: cgsbuggy
        image: 992382723499.dkr.ecr.us-west-2.amazonaws.com/cgs
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cgsbuggy
    k8s-app: cgsbuggy
  name: cgsbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: cgsbuggy
